### ISSUE TITLE
scroll-view组件ios当item项目只有4个的时候，IOS左切换，显示的item会减少，直到最后一个

### ISSUE THREAD

**Issue by sea-lanya** [dcloudio/uni-template-news#3]
scroll-view组件ios当item项目只有4个的时候，IOS左切换，显示的item会减少，直到最后一个

目前默认6个

`tabBars: [{
					id: "tab01",
					name: '最新',
					newsid: 0
				}, {
					id: "tab02",
					name: '大公司',
					newsid: 23
				}, {
					id: "tab03",
					name: '内容',
					newsid: 223
				}, {
					id: "tab04",
					name: '消费',
					newsid: 221
				}, {
					id: "tab05",
					name: '娱乐',
					newsid: 225
				}, {
					id: "tab06",
					name: '区块链',
					newsid: 208
				}, ],
				`

改为

`tabBars: [{
					id: "tab01",
					name: '最新',
					newsid: 0
				}, {
					id: "tab02",
					name: '大公司',
					newsid: 23
				}, {
					id: "tab03",
					name: '内容',
					newsid: 223
				}, {
					id: "tab04",
					name: '消费',
					newsid: 221
				}],
				`

IOS测试，左切换， 就知道了

**Comment by hdx-w** [comment]
更到最新版，已修复
